[/]
clock-format='24h'
clock-show-seconds=true
clock-show-weekday=true
color-scheme='prefer-dark'
cursor-size=24
cursor-theme='Adwaita'
font-antialiasing='grayscale'
font-hinting='slight'
font-name='Inter 11'
font-rgba-order='rgb'
gtk-enable-primary-paste=false
gtk-theme='Arc'
icon-theme='Papirus-Dark'
text-scaling-factor=1.0
toolbar-icons-size='large'
toolbar-style='both-horiz'