# system-files.conf
# Format: source_in_repo:destination_on_system
system/sddm/sddm.conf:/etc/sddm.conf
system/sddm-theme/silent/configs/custom.conf:/usr/share/sddm/themes/silent/configs/custom.conf
system/sddm-theme/silent/metadata.desktop:/usr/share/sddm/themes/silent/metadata.desktop
assets/wallpapers/wallpaper_0.png:/usr/share/sddm/themes/silent/backgrounds/custom_wallpaper.png
system/pacman/pacman.conf:/etc/pacman.conf
