general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = /home/cdoctor/coding/dotfiles/assets/wallpapers/wallpaper_0.png
    blur_passes = 2
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(88c0d0)
    inner_color = rgb(2e3440)
    font_color = rgb(d8dee9)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    dots_center = true
    rounding = 10
}